# Generated by Django 5.0.3 on 2024-04-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='status',
            new_name='agent_id',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='device',
            new_name='desktop_name',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='name',
        ),
        migrations.AddField(
            model_name='agent',
            name='vlan',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='ip_address',
            field=models.CharField(max_length=15),
        ),
    ]
